### ISSUE TITLE
AssertionError: Internal error when reording ONNX operators

### ISSUE THREAD

**Issue by Factos001** [jiazhihao/TASO#30] opened 2019-11-28 06:06 UTC
Hi,
I first download the .onnx model from this repo: 
https://github.com/onnx/models/tree/master/vision/classification/resnet/resnet50

Then I use the code below to load the model
old_model = taso.load_onnx("./resnet50.onnx")

An error message appears that
File "/home/ubuntu/taso/python/taso/__init__.py", line 730, in load_onnx
assert len(node_list) == len(mode.graph.node), "Internal error when reording ONNX operators"

I am wondering how to solve this problem, thanks!

**Comment by jiazhihao** [comment] 2019-12-02 07:46
@leolx7 Thanks for reporting the issue --- it seems the ONNX file does not list operators in a topological ordering and TASO failed to recover the order. Can you point me the ONNX file version you used (realise 1.x or master)? I want to debug this using the same version.

**Comment by Factos001** [comment] 2019-12-02 08:07
@jiazhihao Actually I have tried all these five versions and all of them got the same error.

**Comment by jiazhihao** [comment] 2019-12-02 08:27
Thanks for letting me know. I will debug this issue and get back to you.

**Comment by jiazhihao** [comment] 2019-12-05 00:23
@leolx7 The issue should have been fixed in commit e6fc34398

**Comment by Factos001** [comment] 2019-12-06 07:16
@jiazhihao Thanks for the feedback. I have tried. The error has gone. But it seems that the program skips a lot of operators. Like "Cannot find input tensor for operator: name(Relu_15) type (Relu) (Skipped)". As a result, the output optimized graph has much layers less than the original graph. For example, the output optimized graph for ResNet50 has only 6 layers.

**Comment by jiazhihao** [comment] 2019-12-06 23:03
@leolx7 That is because TASO cannot find the input tensors from the ONNX model. I have tried https://s3.amazonaws.com/download.onnx/models/opset_6/resnet50.tar.gz and it seems to work for me. Which ONNX version are you using?

**Comment by Factos001** [comment] 2019-12-10 07:09
Hi, I am using the master one. I have tried the version you used. The optimized result is basically the same, like the image shown below.
![resnet](https://user-images.githubusercontent.com/29563899/70503559-9fcb5480-1b5e-11ea-8eff-25f13a5ef5ee.png)

**Comment by jiazhihao** [comment] 2019-12-13 22:06
@leolx7 I can reproduce your error on my machine. It is because the master version of ResNet50 uses Sum instead of Add for element-wise addition. I have added the support for Sum in TASO (commit fed32e9cf). The optimized graph looks good on my machine.

It would be great if you can rerun TASO can confirm the fix.

**Comment by Factos001** [comment] 2019-12-18 05:40
@jiazhihao Hi, I use the master version of ResNet50 and rerun TASO. It works well and the optimized graph looks good. Thanks for your patience.

**Closed as completed** 2019-12-18 05:40 UTC
